theme: jekyll-theme-cayman
title: The Candid Startup
url: https://www.thecandidstartup.org
google_analytics: G-W5FLWM10L7
twitter:
  username: ThCandidStartup
utterances:
  issue-term: pathname
  label: blog comment
  theme: github-light
plugins:
  - jekyll-feed
