theme: jekyll-theme-cayman
title: The Candid Startup
url: https://www.thecandidstartup.org
header_page_refs: 
  - blog
  - about
  - contact
  - now
google_analytics: G-W5FLWM10L7
twitter:
  username: ThCandidStartup
author: Tim Wiegand
utterances:
  issue-term: pathname
  label: "blog comment"
  theme: github-light
relative_links:
  enabled: false
  collections: true
feed:
  posts_limit: 20
  excerpt_only: true
paginate: 10
paginate_path: "/blog/page:num/"
collections:
  topics:
    output: true
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-paginate
